"""add variant_id to notification table

Revision ID: 49c5feb1a8e1
Revises: 2af22426ece8
Create Date: 2026-09-06 20:19:30.078459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c5feb1a8e1'
down_revision: Union[str, Sequence[str], None] = '2af22426ece8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'product', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'variant_id')
    # ### end Alembic commands ###
