"""make from_user column nullable in notification table

Revision ID: 6e1bb2f345c3
Revises: a55f5814a54c
Create Date: 2026-09-07 14:28:58.339906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1bb2f345c3'
down_revision: Union[str, Sequence[str], None] = 'a55f5814a54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'from_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'from_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
