"""add one to many relationship between product variant and notification

Revision ID: a55f5814a54c
Revises: 21bc65429f12
Create Date: 2026-09-07 13:52:40.704146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55f5814a54c'
down_revision: Union[str, Sequence[str], None] = '21bc65429f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_variant_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'productvariant', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_variant_id_fkey'), 'notification', 'product', ['variant_id'], ['id'])
    # ### end Alembic commands ###
